# Generated by Django 5.1.2 on 2024-10-29 07:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3, verbose_name='валюта')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость')),
            ],
            options={
                'verbose_name': 'цена',
                'verbose_name_plural': 'цены',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'тип товара',
                'verbose_name_plural': 'типы товаров',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='название')),
                ('qty', models.PositiveIntegerField(verbose_name='количество')),
                ('barcode', models.CharField(max_length=64, unique=True, verbose_name='штрихкод')),
                ('date_update', models.DateField(auto_now=True, verbose_name='дата обновления')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='goods.price', verbose_name='цена')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.type', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
